export enum ErrorMessage {
    GLOBAL_ERROR_MESSAGE = 'Une erreur est survenue.',
    GLOBAL_NOT_FOUND_MESSAGE = 'Ressource introuvable.',
    TOO_MANY_REQUESTS = 'Trop de tentatives, réessayez dans 1 minute.',
    REFRESH_TOKEN_ERROR = 'Refresh token invalide ou expiré.',
    UNAUTHORIZED_MESSAGE = 'Vous n’êtes pas autorisé.',
    USERNAME_EMAIL_ALREADY_EXISTS = 'Le nom d’utilisateur ou l’email sont déjà utilisé.',
    USERNAME_ALREADY_EXISTS = 'Le nom d’utilisateur est déjà utilisé.',
    UPDATE_ERROR_MESSAGE = 'Echec de la modification.',
    DELETE_ERROR_MESSAGE = 'Echec de la suppression.',
    USER_NOT_FOUND = "Utilisateur introuvable",
    USER_LOGIN_ERROR = "Email ou mot de passe incorrect.",
    USER_ACCOUNT_DISABLED = "Ce compte a été désactivé.",
    USER_CANNOT_MODIFY_OTHER = "Vous ne pouvez modifier que votre propre compte.",
    SPACE_ORGANISATION_ALREADY_EXISTS = "L'organisation spatiale existe déjà.",
    SPACE_ORGANISATION_NOT_FOUND = "Organisation spatiale introuvable",
    SPACE_ORGANISATION_CANNOT_MODIFY_OTHER = "Vous ne pouvez modifier que votre propre organisation spatiale.",
    AMATEUR_OWNER_NOT_FOUND = "Propriétaire amateur introuvable",
    AMATEUR_OWNER_CONSENT_REQUIRES_NAME = "Le nom et prénom sont requis si le consentement à l'affichage est donné",
    AMATEUR_OWNER_CONSENT_REQUIRES_CONSENT = "Le consentement à l'affichage est requis si le nom et prénom sont fournis",
    AMATEUR_OWNER_CANNOT_MODIFY_OTHER = "Vous ne pouvez modifier que votre propre propriétaire amateur.",
    TELESCOPE_NOT_FOUND = "Télescope introuvable",
    GAME_NOT_AVAILABLE = "Le jeu n'est pas disponible dans ce mode.",
    GAME_SESSION_NOT_FOUND = "Session de jeu introuvable",
    GAME_SESSION_ALREADY_FINISHED = "La session de jeu est déjà terminée.",
    GAME_CONFIG_NOT_FOUND = "Configuration de jeu introuvable.",
    GAME_CONFIG_ALREADY_EXISTS = "La configuration de jeu existe déjà pour ce type et ce mode.",
}