export enum SuccessMessage {
    USER_CREATED = 'Compte créé avec succès',
    USER_UPDATED = 'Compte mis à jour avec succès',
    USER_DELETED = 'Compte supprimé avec succès',
    USER_FETCHED_ALL = 'Utilisateurs récupérés avec succès',
    USER_FETCHED_BY_ID = 'Utilisateur récupéré avec succès',
    USER_PROFIL_FETCHED = 'Profile récupéré avec succès',
    USER_LOGGED_IN = 'Connexion réussie',
    USER_LOGGED_OUT = 'Déconnexion réussie',
    TOKEN_REFRESHED = 'Token rafraîchi avec succès',
    SPACE_ORGANISATION_FETCHED_ALL = "Organisations spatiales récupérées avec succès",
    SPACE_ORGANISATION_FETCHED_BY_ID = "Organisation spatiale récupérée avec succès",
    SPACE_ORGANISATION_CREATED = "Organisation spatiale créée avec succès",
    SPACE_ORGANISATION_UPDATED = "Organisation spatiale mise à jour avec succès",
    SPACE_ORGANISATION_DELETED = "Organisation spatiale supprimée avec succès",
    AMATEUR_OWNER_FETCHED_ALL = "Propriétaires amateurs récupérés avec succès",
    AMATEUR_OWNER_FETCHED_BY_ID = "Propriétaire amateur récupéré avec succès",
    AMATEUR_OWNER_CREATED = "Propriétaire amateur créé avec succès",
    AMATEUR_OWNER_UPDATED = "Propriétaire amateur mis à jour avec succès",
    AMATEUR_OWNER_DELETED = "Propriétaire amateur supprimé avec succès",
    TELESCOPE_FETCHED_ALL = "Télescopes récupérés avec succès",
    TELESCOPE_FETCHED_BY_ID = "Télescope récupéré avec succès",
    TELESCOPE_CREATED = "Télescope créé avec succès",
    TELESCOPE_UPDATED = "Télescope mis à jour avec succès",
    TELESCOPE_DELETED = "Télescope supprimé avec succès",
}